image: nixos/nix

stages:
  - build
  - test
  - ci_status

### Build

# Build Fencer and put into ./out/bin/fencer
compile:
  stage: build
  script:
    - nix-build -o out
  artifacts:
    paths:
      - out/

# Build the Go integration test and put into ./out-bin/bin/test_integration_go
compile_integration:
  stage: build
  script:
    - nix-build test_integration_go -o out
  artifacts:
    paths:
      - out-bin/

### Test

integration:
  stage: test
  script:
    - RUNTIME_ROOT=./test_integration_go/config RUNTIME_SUBDIRECTORY=ratelimit ./out/bin/fencer &
    - sleep 0.1
    - ./out-bin/bin/test_integration_go
    - kill $!

### CI status

success:
  stage: ci_status
  before_script:
    - ""
  after_script:
    - ""
  script:
    - BUILD_STATUS=passed BUILD_KEY=push nix-shell -p bash curl --run .gitlab/build_status.sh
  when: on_success

failure:
  stage: ci_status
  before_script:
    - ""
  after_script:
    - ""
  script:
    - BUILD_STATUS=failed BUILD_KEY=push nix-shell -p bash curl --run .gitlab/build_status.sh
  when: on_failure
